name: maxway_clone
description: "Max Way clone"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  # di
  get_it: ^7.7.0
  # equatable
  equatable: ^2.0.5
  # state manager
  flutter_bloc: ^8.1.5
  # hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # path
  path_provider: ^2.1.3
  # rest api
  dio: ^5.4.3+1
  dio_retry_plus: ^2.0.7
  # chuck
  chuck_interceptor: ^2.1.7
  # box
  gap: ^3.0.1
  #retrofit: ^4.1.0
  retrofit: ^4.1.0
  # router
  go_router: ^14.0.1
  # svg
  flutter_svg: ^2.0.10+1
  # url launchers
  url_launcher: ^6.2.6
  # otp autofill
  otp_autofill_plus: ^1.0.5
  # sms autofill
  pin_input_text_field: ^4.5.1
  pinput: ^5.0.0
  #carousel_slider
  carousel_slider_plus: ^6.0.0
  # package info
  package_info_plus: ^8.0.0
  # cached network image
  cached_network_image: ^3.3.1
  # firebase
  firebase_core: ^2.30.1
  firebase_analytics: ^10.10.4
  firebase_messaging: ^14.9.1
  firebase_remote_config: ^4.4.4
  # local notification
  flutter_local_notifications: ^17.1.0
  zoom_tap_animation: ^1.1.0
  # text formater
  mask_text_input_formatter: ^2.9.0
  json_annotation: ^4.9.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  formz: ^0.7.0
  rxdart: ^0.27.7
  #yandex_mapkit
  yandex_mapkit: ^4.1.0
  #geoclactor
  geolocator: ^12.0.0
  #skeletonizer
  skeletonizer: ^1.4.1+1
  #firebase
  flag: ^7.0.0
  #qr code
  hydrated_bloc: ^9.1.5

dev_dependencies:
  analyzer: ^6.7.0
  bloc_test: ^9.1.7
  build_runner: ^2.4.11
  flutter_lints: ^3.0.2
  hive_generator: ^2.0.1
  retrofit_generator: '>=7.0.0 <8.0.0'
  json_serializable: ^6.8.0
  #  freezed: ^2.5.7
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/fonts/
    - assets/locale/

  fonts:
    - family: Sf pro Display
      fonts:
        - asset: assets/fonts/SFPRODISPLAYBLACKITALIC.OTF
        - asset: assets/fonts/SFPRODISPLAYBOLD.OTF
        - asset: assets/fonts/SFPRODISPLAYHEAVYITALIC.OTF
        - asset: assets/fonts/SFPRODISPLAYLIGHTITALIC.OTF
        - asset: assets/fonts/SFPRODISPLAYMEDIUM.OTF
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF
        - asset: assets/fonts/SFPRODISPLAYSEMIBOLDITALIC.OTF
        - asset: assets/fonts/SFPRODISPLAYTHINITALIC.OTF
        - asset: assets/fonts/SFPRODISPLAYULTRALIGHTITALIC.OTF
          style: italic

